// Сборка плоского GAS-бандла: dist/gm-slots.gas.js. Формат и приём — как в gm-stats:
// esbuild-IIFE (globalName GmSlots) прячет внутренности, подвал алиасов `var X = GmSlots.X;`
// поднимает публичные имена глобальными функциями Apps Script.
//
// Список имён берётся из самого бандла — руками не дублируется и не протухает.

import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';

const result = await build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  write: false,
  format: 'iife',
  globalName: 'GmSlots',
  platform: 'neutral',
  target: 'es2020',
  legalComments: 'none'
});

const iife = result.outputFiles[0].text;

const ctx = {};
vm.createContext(ctx);
vm.runInContext(iife, ctx);
const names = Object.keys(ctx.GmSlots).sort();
if (!names.length) throw new Error('build-gas: бандл не отдал ни одного экспорта');

const aliases = names.map((n) => `var ${n} = GmSlots.${n};`).join('\n');
const out =
  '// @gmbl/gm-slots — GAS bundle. AUTO-GENERATED by build-gas.mjs. Do not edit.\n' +
  '// Плоский файл для Apps Script: ни import, ни export. Внутренности — в замыкании GmSlots,\n' +
  `// наружу ${names.length} глобальных имён (см. подвал файла).\n\n` +
  iife +
  '\n// --- Публичные имена ядра как глобальные функции Apps Script ---\n' +
  aliases + '\n';

mkdirSync('dist', { recursive: true });
writeFileSync('dist/gm-slots.gas.js', out, 'utf8');
console.log(`GAS bundle: dist/gm-slots.gas.js (${names.length} имён, ${out.length} байт)`);
